openapi: 3.0.1
info:
  title: Kacha-Tunes_Transfer_USDtoUSD
  description: API Definition of Kacha-Tunes_Transfer
  version: 1.0.0
servers:
- url: http://localhost:8290/NIB/api/kacha/transfer/usd-usd
paths:
  /:
    post:
      responses:
        default:
          description: Default response
