openapi: 3.0.1
info:
  title: Kacha-Tunes_USD_ETB
  description: API Definition of Kacha-Tunes_USD_ETB
  version: 1.0.0
servers:
- url: http://localhost:8290/NIB/api/kacha/transfer/usd-etb
paths:
  /:
    post:
      responses:
        default:
          description: Default response
