openapi: 3.0.1
info:
  title: Kacha-Tunes_Balance
  description: API Definition of Kacha-Tunes_Balance
  version: 1.0.0
servers:
- url: http://localhost:8290/NIB/api/kacha/balance
paths:
  /:
    post:
      responses:
        default:
          description: Default response
