openapi: 3.0.1
info:
  title: Kacha-Tunes_ExchangeRate
  description: API Definition of Kacha-Tunes_ExchangeRate
  version: 1.0.0
servers:
- url: http://localhost:8290/NIB/api/kacha/exchangeRate
paths:
  /:
    post:
      responses:
        default:
          description: Default response
