openapi: 3.0.1
info:
  title: Kacha-Tunes_ExchangeRateAll
  description: API Definition of Kacha-Tunes_ExchangeRateAll
  version: 1.0.0
servers:
- url: http://localhost:8290/NIB/api/kacha/exchangeRate/all
paths:
  /:
    get:
      responses:
        default:
          description: Default response
